default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1

development:
  <<: *default
  database: arbitrager_dev

test:
  <<: *default
  database: arbitrager_test

production:
  <<: *default
  database: arbitrager
  username: sample
  password: <%= ENV['DATABASE_PASSWORD'] %>
